<?xml version="1.0"?>
<package format="3">
  <name>keypoint_msg</name>
  <version>0.0.1</version>
  <description>Custom messages used for sending described keypoints</description>

  <maintainer email="anton.backhaus@unibw.de">Anton Backhaus</maintainer>
  <license>TODO</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Message generation -->
  <build_depend>rosidl_default_generators</build_depend>

  <!-- Dependencies for messages -->
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>

  <!-- Runtime -->
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  <!-- Export -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>