<?xml version="1.0"?>
<package format="3">
  <name>yolopoint</name>
  <version>0.0.1</version>
  <description>Keypoint and object detector</description>

  <maintainer email="anton.backhaus@unibw.de">anba</maintainer>
  <maintainer email="zahra.boroujeni@gmail.com">Dan Umeda</maintainer>
  <license>GNU</license>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>object_instance_msgs</depend>
  <depend>keypoint_msg</depend>

  <!-- Optional but recommended -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- Export -->
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>